### ISSUE TITLE
Fix Invalid JSON RPC response:

### ISSUE THREAD

**Issue by dadepo** [ChainSafe/eth2-light-client-demo#47]
**Describe the bug**

After the prater merge (and upgrade to lodestar v1) when light client is initiated successfully, the eth1 related part of the UI displays the following error: 

```
Invalid JSON RPC response: ""
Error: Invalid JSON RPC response: ""
    at Object.InvalidResponse (https://lodestar-lightclient.chainsafe.io/static/js/main.ed0b57d6.js:2:2019014)
    at n.onreadystatechange (https://lodestar-lightclient.chainsafe.io/static/js/main.ed0b57d6.js:2:2164400)
```

**Comment by jeluard** [comment]
@dadepo  Is this still relevant? I can't reproduce this.

**Comment by dadepo** [comment]
@jeluardcha, I can't really remember the details, it has been a while...so probably no longer relevant. It can be closed :)
